#!/usr/bin/python

import subprocess;
import shlex;
import sys;
#subprocess.call(['ifconfig','p2p0']);

inputString= raw_input("Input command: ")

print "The input command is: " + inputString
#cmdline=inputString.split(' ')

cmdline=shlex.split(inputString);
#args= shlex.split(cmdline);
print  cmdline
#print args
subprocess.Popen(cmdline);

# Test Popen with file name containing special char.(Works)
#arglist=['cat','\\\\asdf']
#subprocess.Popen(arglist);

#For wildcard char '*', you can't put it in a list. It will definitely fail.
#subprocess.Popen("cat *", shell=True);
#arglist2=['cat','\*']          //Not working. Use Shell=True instead.